"""Add register date for user

Revision ID: 696915195f20
Revises: 651ee1e3396c
Create Date: 2022-05-27 08:37:17.679759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '696915195f20'
down_revision = '651ee1e3396c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered')
    # ### end Alembic commands ###
